import React, { useState } from 'react';
import { Calculator, Clock, DollarSign, ArrowUpRight, TrendingUp, Landmark, ShieldCheck } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from './ui/card';

const AGENCY_SAVINGS = [
  { agency: 'NHAI / National Expressways', typicalPipeline: '45 Corridors / yr', delaySaved: '180 Months', feeSaved: '₹15.75 Cr', metric: '6 Months Accelerated Commissioning' },
  { agency: 'SECI / Solar Power Parks', typicalPipeline: '30 Ultra-Mega Parks', delaySaved: '120 Months', feeSaved: '₹10.50 Cr', metric: 'Zero GIB Avian Corridor Delay' },
  { agency: 'State Water & Irrigation Depts', typicalPipeline: '25 Hydro Projects', delaySaved: '100 Months', feeSaved: '₹8.75 Cr', metric: 'Automated Submergence Survey' },
  { agency: 'State Industrial Dev Corps (SIDC)', typicalPipeline: '40 Manufacturing Hubs', delaySaved: '160 Months', feeSaved: '₹14.00 Cr', metric: 'Instant ZLD Effluent Certification' },
];

export default function CalculatorSection() {
  const [projects, setProjects] = useState(120);
  const [months, setMonths] = useState(4.5);

  const monthsSaved = Math.round(projects * months);
  const capitalPreservedCrores = ((projects * 25000 * 0.98) / 100000).toFixed(2);
  const consultantFeesSavedCrores = ((projects * 3500000) / 10000000).toFixed(2);

  return (
    <section id="calculator" className="py-8 sm:py-12 border-t relative overflow-hidden bg-gradient-to-b from-[#e6f8ee]/70 via-[#f2fbf6] to-[#f4f1ea]" style={{ borderColor: 'var(--border-subtle, #d5cfc2)' }}>
      {/* Ambient Mint / Lime Glow */}
      <div className="absolute top-10 left-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none -z-10" />
      <div className="absolute bottom-10 right-10 w-80 h-80 bg-teal-500/10 rounded-full blur-3xl pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-4 relative z-10">
        <Card className="p-4 sm:p-6 space-y-4 scroll-reveal shadow-sm">
          {/* Header */}
          <div className="max-w-2xl mb-2 text-left">
            <h3
              className="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight mb-1.5"
              style={{ color: 'var(--text-main, #1a1d1a)' }}
            >
              Estimated National Time &amp; Budget Savings
            </h3>
            <p className="text-sm sm:text-base leading-relaxed" style={{ color: 'var(--text-muted, #5e625a)' }}>
              Projected savings generated by replacing slow manual paperwork with instant 0.38-second automated compliance checks.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-start">
            {/* Input Sliders (6 Cols) */}
            <div className="lg:col-span-6 space-y-3.5">
              <div
                className="p-3.5 sm:p-4 rounded border bg-emerald-50/60 border-emerald-200"
              >
                <div className="flex justify-between items-center mb-1.5 text-xs sm:text-sm font-medium" style={{ color: 'var(--text-main, #1a1d1a)' }}>
                  <span className="text-xs sm:text-sm font-mono text-emerald-950 font-semibold">Annual Number of Projects</span>
                  <span className="font-mono font-bold text-xs sm:text-sm text-emerald-800">
                    {projects} Projects / Year
                  </span>
                </div>
                <input
                  type="range"
                  min="10"
                  max="500"
                  step="10"
                  value={projects}
                  onChange={(e) => setProjects(parseInt(e.target.value, 10))}
                  className="w-full h-1.5 rounded appearance-none cursor-pointer"
                  style={{
                    accentColor: 'var(--color-primary, #284e3a)',
                    backgroundColor: '#c4dfd0',
                  }}
                />
              </div>

              <div
                className="p-3.5 sm:p-4 rounded border bg-amber-50/60 border-amber-200"
              >
                <div className="flex justify-between items-center mb-1.5 text-xs sm:text-sm font-medium" style={{ color: 'var(--text-main, #1a1d1a)' }}>
                  <span className="text-xs sm:text-sm font-mono text-amber-950 font-semibold">Average Manual Review Delay (Months)</span>
                  <span className="font-mono font-bold text-xs sm:text-sm text-amber-800">
                    {months.toFixed(1)} Months / Project
                  </span>
                </div>
                <input
                  type="range"
                  min="1"
                  max="12"
                  step="0.5"
                  value={months}
                  onChange={(e) => setMonths(parseFloat(e.target.value))}
                  className="w-full h-1.5 rounded appearance-none cursor-pointer"
                  style={{
                    accentColor: 'var(--color-secondary, #9c6519)',
                    backgroundColor: '#e9d6b8',
                  }}
                />
              </div>
            </div>

            {/* Computed Ledger Results (6 Cols) */}
            <div className="lg:col-span-6 grid grid-cols-2 gap-3.5">
              <div
                className="p-3.5 sm:p-4 rounded border bg-emerald-50/70 border-emerald-300/80 shadow-xs"
              >
                <div className="text-xs font-mono uppercase font-bold text-emerald-800">
                  Total Review Time Saved
                </div>
                <div className="text-2xl sm:text-3xl font-mono font-bold mt-1 text-emerald-950">
                  {monthsSaved} Months
                </div>
                <p className="text-xs sm:text-sm mt-1 leading-relaxed text-emerald-900/80">
                  Equivalent to {(monthsSaved / 12).toFixed(1)} years of manual review
                </p>
              </div>

              <div
                className="p-3.5 sm:p-4 rounded border bg-amber-50/70 border-amber-300/80 shadow-xs"
              >
                <div className="text-xs font-mono uppercase font-bold text-amber-800">
                  Consultant Fees Saved
                </div>
                <div className="text-2xl sm:text-3xl font-mono font-bold mt-1 text-amber-950">
                  ₹{consultantFeesSavedCrores} Cr
                </div>
                <p className="text-xs sm:text-sm mt-1 leading-relaxed text-amber-900/80">
                  Preserved in project budgets
                </p>
              </div>
            </div>
          </div>

          {/* Agency & Department Level Impact Breakdown */}
          <div
            className="p-4 sm:p-5 rounded border mt-2 bg-stone-50/80"
            style={{
              borderColor: 'var(--border-subtle, #d5cfc2)',
            }}
          >
            <div className="flex items-center justify-between pb-2.5 mb-2.5 border-b" style={{ borderColor: 'var(--border-subtle, #d5cfc2)' }}>
              <span className="text-sm sm:text-base font-sans font-bold" style={{ color: 'var(--text-main, #1a1d1a)' }}>
                Government Agency &amp; Infrastructure Projects
              </span>
              <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-emerald-100 text-emerald-900 border border-emerald-300">
                Annual Benchmark
              </span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs sm:text-sm font-sans">
                <thead className="font-mono text-xs uppercase border-b" style={{ borderColor: 'var(--border-subtle, #d5cfc2)', color: 'var(--text-muted, #5e625a)' }}>
                  <tr>
                    <th className="pb-2">Organization / Agency</th>
                    <th className="pb-2">Annual Projects</th>
                    <th className="pb-2">Time Saved</th>
                    <th className="pb-2">Fees Saved</th>
                    <th className="pb-2">Key Benefit</th>
                  </tr>
                </thead>
                <tbody className="divide-y text-xs sm:text-sm" style={{ borderColor: 'var(--border-subtle, #d5cfc2)', color: 'var(--text-main, #1a1d1a)' }}>
                  {AGENCY_SAVINGS.map((ag, idx) => (
                    <tr key={idx} className="hover:bg-emerald-50/40 transition-colors">
                      <td className="py-2.5 font-semibold">{ag.agency}</td>
                      <td className="py-2.5 font-mono">{ag.typicalPipeline}</td>
                      <td className="py-2.5 font-mono font-bold text-emerald-700">{ag.delaySaved}</td>
                      <td className="py-2.5 font-mono font-bold text-amber-700">{ag.feeSaved}</td>
                      <td className="py-2.5">{ag.metric}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Card>
      </div>
    </section>
  );
}
