import React, { useState } from 'react';
import { Calculator, Clock, DollarSign, ArrowUpRight, TrendingUp, Landmark, ShieldCheck } from 'lucide-react';

const AGENCY_SAVINGS = [
  { agency: 'NHAI / National Expressways', typicalPipeline: '45 Corridors / yr', delaySaved: '180 Months', feeSaved: '₹15.75 Cr', metric: '6 Months Accelerated Commissioning' },
  { agency: 'SECI / Solar Power Parks', typicalPipeline: '30 Ultra-Mega Parks', delaySaved: '120 Months', feeSaved: '₹10.50 Cr', metric: 'Zero GIB Avian Corridor Delay' },
  { agency: 'State Water & Irrigation Depts', typicalPipeline: '25 Hydro Projects', delaySaved: '100 Months', feeSaved: '₹8.75 Cr', metric: 'Automated Submergence Survey' },
  { agency: 'State Industrial Dev Corps (SIDC)', typicalPipeline: '40 Manufacturing Hubs', delaySaved: '160 Months', feeSaved: '₹14.00 Cr', metric: 'Instant ZLD Effluent Certification' },
];

export default function CalculatorSection() {
  const [projects, setProjects] = useState(120);
  const [months, setMonths] = useState(4.5);

  const monthsSaved = Math.round(projects * months);
  const capitalPreservedCrores = ((projects * 25000 * 0.98) / 100000).toFixed(2);
  const consultantFeesSavedCrores = ((projects * 3500000) / 10000000).toFixed(2);

  return (
    <section id="calculator" className="py-10 sm:py-14 border-t" style={{ borderColor: 'var(--border-subtle, #d8d4ca)' }}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        <div
          className="rounded-xl border p-5 sm:p-7 shadow-xs space-y-6"
          style={{
            backgroundColor: 'var(--bg-card, #fbfaf6)',
            borderColor: 'var(--border-subtle, #d8d4ca)',
          }}
        >
          {/* Header */}
          <div className="max-w-2xl">
            <div
              className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[11px] font-mono mb-2"
              style={{
                backgroundColor: 'var(--color-primary-light, #e2ebe5)',
                color: 'var(--color-primary-text, #244737)',
              }}
            >
              <Calculator className="w-3.5 h-3.5" />
              <span>CLEARANCE EFFICIENCY &amp; FINANCIAL LEDGER</span>
            </div>
            <h3
              className="text-xl sm:text-2xl font-serif font-bold tracking-tight"
              style={{ color: 'var(--text-main, #20231f)' }}
            >
              Estimated National Time &amp; Budget Savings
            </h3>
            <p className="text-xs sm:text-sm mt-1" style={{ color: 'var(--text-muted, #73766f)' }}>
              Projected pipeline savings generated by replacing manual paper screening with instant 0.38-second automated GIS compliance.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
            {/* Input Sliders (6 Cols) */}
            <div className="lg:col-span-6 space-y-4">
              <div
                className="p-3.5 rounded-lg border"
                style={{
                  backgroundColor: 'var(--bg-card-subtle, #edeae1)',
                  borderColor: 'var(--border-subtle, #d8d4ca)',
                }}
              >
                <div className="flex justify-between items-center mb-1 text-xs font-medium" style={{ color: 'var(--text-main, #20231f)' }}>
                  <span>Annual Infrastructure Pipeline (Projects)</span>
                  <span className="font-mono font-bold" style={{ color: 'var(--color-primary, #315c48)' }}>
                    {projects} Projects / Year
                  </span>
                </div>
                <input
                  type="range"
                  min="10"
                  max="500"
                  step="10"
                  value={projects}
                  onChange={(e) => setProjects(parseInt(e.target.value, 10))}
                  className="w-full h-1.5 rounded appearance-none cursor-pointer"
                  style={{
                    accentColor: 'var(--color-primary, #315c48)',
                    backgroundColor: 'var(--border-subtle, #d8d4ca)',
                  }}
                />
              </div>

              <div
                className="p-3.5 rounded-lg border"
                style={{
                  backgroundColor: 'var(--bg-card-subtle, #edeae1)',
                  borderColor: 'var(--border-subtle, #d8d4ca)',
                }}
              >
                <div className="flex justify-between items-center mb-1 text-xs font-medium" style={{ color: 'var(--text-main, #20231f)' }}>
                  <span>Average Manual Committee Delay (Months)</span>
                  <span className="font-mono font-bold" style={{ color: 'var(--color-secondary, #b77927)' }}>
                    {months.toFixed(1)} Months / Project
                  </span>
                </div>
                <input
                  type="range"
                  min="1"
                  max="12"
                  step="0.5"
                  value={months}
                  onChange={(e) => setMonths(parseFloat(e.target.value))}
                  className="w-full h-1.5 rounded appearance-none cursor-pointer"
                  style={{
                    accentColor: 'var(--color-secondary, #b77927)',
                    backgroundColor: 'var(--border-subtle, #d8d4ca)',
                  }}
                />
              </div>
            </div>

            {/* Computed Ledger Results (6 Cols) */}
            <div className="lg:col-span-6 grid grid-cols-2 gap-3">
              <div
                className="p-3.5 rounded-lg border"
                style={{
                  backgroundColor: 'var(--bg-card-subtle, #edeae1)',
                  borderColor: 'var(--border-subtle, #d8d4ca)',
                }}
              >
                <div className="text-[10px] font-mono uppercase" style={{ color: 'var(--text-muted, #73766f)' }}>
                  Cumulative Review Time Saved
                </div>
                <div className="text-2xl font-mono font-bold mt-1" style={{ color: 'var(--color-primary, #315c48)' }}>
                  {monthsSaved} Months
                </div>
                <p className="text-[11px] mt-0.5" style={{ color: 'var(--text-muted, #73766f)' }}>
                  Equivalent to {(monthsSaved / 12).toFixed(1)} committee-years
                </p>
              </div>

              <div
                className="p-3.5 rounded-lg border"
                style={{
                  backgroundColor: 'var(--bg-card-subtle, #edeae1)',
                  borderColor: 'var(--border-subtle, #d8d4ca)',
                }}
              >
                <div className="text-[10px] font-mono uppercase" style={{ color: 'var(--text-muted, #73766f)' }}>
                  Routine Consultant Fees Saved
                </div>
                <div className="text-2xl font-mono font-bold mt-1" style={{ color: 'var(--color-secondary, #b77927)' }}>
                  ₹{consultantFeesSavedCrores} Cr
                </div>
                <p className="text-[11px] mt-0.5" style={{ color: 'var(--text-muted, #73766f)' }}>
                  Preserved in project budgets
                </p>
              </div>
            </div>
          </div>

          {/* Agency & Department Level Impact Breakdown (Fills empty space) */}
          <div
            className="p-4 rounded-lg border"
            style={{
              backgroundColor: 'var(--bg-card-subtle, #edeae1)',
              borderColor: 'var(--border-subtle, #d8d4ca)',
            }}
          >
            <div className="flex items-center justify-between pb-2 mb-2 border-b" style={{ borderColor: 'var(--border-subtle, #d8d4ca)' }}>
              <span className="text-xs font-serif font-bold" style={{ color: 'var(--text-main, #20231f)' }}>
                Government Agency &amp; PSU Infrastructure Projections
              </span>
              <span className="text-[10px] font-mono" style={{ color: 'var(--color-primary, #315c48)' }}>
                Annual Benchmark
              </span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-sans">
                <thead className="font-mono text-[10px] border-b" style={{ borderColor: 'var(--border-subtle, #d8d4ca)', color: 'var(--text-muted, #73766f)' }}>
                  <tr>
                    <th className="pb-1.5">Government Body / PSU</th>
                    <th className="pb-1.5">Sample Annual Pipeline</th>
                    <th className="pb-1.5">Review Time Saved</th>
                    <th className="pb-1.5">Consultant Fees Saved</th>
                    <th className="pb-1.5">Primary Operational Impact</th>
                  </tr>
                </thead>
                <tbody className="divide-y text-[11px]" style={{ borderColor: 'var(--border-subtle, #d8d4ca)', color: 'var(--text-main, #20231f)' }}>
                  {AGENCY_SAVINGS.map((ag, idx) => (
                    <tr key={idx} className="hover:bg-[#fbfaf6]/40">
                      <td className="py-2 font-semibold">{ag.agency}</td>
                      <td className="py-2 font-mono">{ag.typicalPipeline}</td>
                      <td className="py-2 font-mono font-bold" style={{ color: 'var(--color-primary, #315c48)' }}>{ag.delaySaved}</td>
                      <td className="py-2 font-mono font-bold" style={{ color: 'var(--color-secondary, #b77927)' }}>{ag.feeSaved}</td>
                      <td className="py-2">{ag.metric}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
